In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\user\ecommerce_sales_customer_analytics_150k.csv")
print(df)

          order_id  order_date order_time order_status sales_channel  \
0       ORD-301242  2023-11-06   16:37:47    Completed    Mobile App
1       ORD-773460  2025-12-24   01:22:36    Completed       Website
2       ORD-449374  2021-07-05   14:24:21    Completed    Mobile App
3       ORD-567636  2023-01-21   07:20:26    Completed  Social Media
4       ORD-820028  2022-05-13   09:46:21    Completed  Social Media
...            ...         ...        ...          ...           ...
138111  ORD-481534  2025-09-27   13:00:50    Completed    Mobile App
138112  ORD-487614  2023-07-22   09:13:25     Returned  Social Media
138113  ORD-248062  2025-09-08   18:30:32    Cancelled    Mobile App
138114  ORD-252033  2022-04-06   14:50:07    Completed  Social Media
138115  ORD-528577  2022-11-23   11:46:00    Completed    Mobile App

        customer_id     customer_name  customer_age  gender customer_segment  \
0       CUST-003102      Jasmine Ryan            55    Male         Consumer
1       CUST-003124       Scott Chase            26    Male          Premium
2       CUST-012496      Marc Wheeler            69  Female          Premium
3       CUST-023928    Jennifer Smith            65    Male         Consumer
4       CUST-012730      Jessica Wang            34  Female         Consumer
...             ...               ...           ...     ...              ...
138111  CUST-007151        Donna Ruiz            41  Female         Consumer
138112  CUST-006686    Jeremy Aguirre            40    Male          Premium
138113  CUST-017497  Timothy Williams            39  Female         Consumer
138114  CUST-005723    Charles Hanson            46  Female         Consumer
138115  CUST-006809       John Miller            28    Male         Consumer

        ... discount_amount tax_amount shipping_cost net_sales product_cost  \
0       ...          477.89      61.07         12.03    945.40       588.33
1       ...         1456.06     320.83          9.00   2018.41      2031.88
2       ...           97.30      29.79         13.05    468.35       257.73
3       ...           53.34      34.39         20.85    546.52       277.84
4       ...          133.63     421.35         23.03   2785.27      1231.88
...     ...             ...        ...           ...       ...          ...
138111  ...            8.84      14.28          6.15    224.42       101.77
138112  ...            0.00     147.30          9.18   2260.80      1246.73
138113  ...            0.00     372.37         26.94   2261.16       970.95
138114  ...          174.60     130.58         84.39   2080.38      1042.40
138115  ...          417.27     102.26          9.09   1572.22       884.46

         profit profit_margin_percentage customer_lifetime_value  \
0        345.04                    36.50                12459.68
1        -22.47                    -1.11                13032.48
2        197.57                    42.18                 6159.44
3        247.83                    45.35                 5638.30
4       1530.36                    54.94                13240.10
...         ...                      ...                     ...
138111   116.50                    51.91                18182.63
138112  1004.89                    44.45                10004.74
138113  1263.27                    55.87                16442.68
138114   953.59                    45.84                 8047.00
138115   678.67                    43.17                 4107.38

       is_repeat_customer customer_order_count
0                    True                   11
1                    True                   11
2                    True                    6
3                    True                    7
4                    True                    8
...                   ...                  ...
138111               True                   14
138112               True                   10
138113               True                   15
138114               True                    5
138115               True                    5

[138116 rows x 46 columns]

In [2]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 46 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  str
 1   order_date                138116 non-null  str
 2   order_time                138116 non-null  str
 3   order_status              138116 non-null  str
 4   sales_channel             138116 non-null  str
 5   customer_id               138116 non-null  str
 6   customer_name             138116 non-null  str
 7   customer_age              138116 non-null  int64
 8   gender                    138116 non-null  str
 9   customer_segment          138116 non-null  str
 10  customer_type             138116 non-null  str
 11  customer_city             138116 non-null  str
 12  customer_state            138116 non-null  str
 13  customer_country          138116 non-null  str
 14  region                    138116 non-null  str
 15  customer_postal_code      138116 non-null  int64
 16  payment_method            138116 non-null  str
 17  payment_status            138116 non-null  str
 18  currency                  138116 non-null  str
 19  shipping_method           138116 non-null  str
 20  warehouse                 138116 non-null  str
 21  delivery_days             113559 non-null  float64
 22  estimated_delivery_days   113559 non-null  float64
 23  delivery_status           138116 non-null  str
 24  return_status             9462 non-null    str
 25  return_reason             9462 non-null    str
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  str
 28  customer_review           113559 non-null  str
 29  marketing_channel         138116 non-null  str
 30  campaign_name             54883 non-null   str
 31  coupon_code               27614 non-null   str
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  float64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
dtypes: bool(1), float64(12), int64(6), str(27)
memory usage: 47.6 MB
None

In [3]:
print(df.columns)

Index(['order_id', 'order_date', 'order_time', 'order_status', 'sales_channel',
       'customer_id', 'customer_name', 'customer_age', 'gender',
       'customer_segment', 'customer_type', 'customer_city', 'customer_state',
       'customer_country', 'region', 'customer_postal_code', 'payment_method',
       'payment_status', 'currency', 'shipping_method', 'warehouse',
       'delivery_days', 'estimated_delivery_days', 'delivery_status',
       'return_status', 'return_reason', 'customer_rating', 'review_sentiment',
       'customer_review', 'marketing_channel', 'campaign_name', 'coupon_code',
       'loyalty_points_earned', 'loyalty_points_redeemed', 'quantity',
       'gross_sales', 'discount_amount', 'tax_amount', 'shipping_cost',
       'net_sales', 'product_cost', 'profit', 'profit_margin_percentage',
       'customer_lifetime_value', 'is_repeat_customer',
       'customer_order_count'],
      dtype='str')

In [5]:
print(df.describe)

<bound method NDFrame.describe of           order_id  order_date order_time order_status sales_channel  \
0       ORD-301242  2023-11-06   16:37:47    Completed    Mobile App
1       ORD-773460  2025-12-24   01:22:36    Completed       Website
2       ORD-449374  2021-07-05   14:24:21    Completed    Mobile App
3       ORD-567636  2023-01-21   07:20:26    Completed  Social Media
4       ORD-820028  2022-05-13   09:46:21    Completed  Social Media
...            ...         ...        ...          ...           ...
138111  ORD-481534  2025-09-27   13:00:50    Completed    Mobile App
138112  ORD-487614  2023-07-22   09:13:25     Returned  Social Media
138113  ORD-248062  2025-09-08   18:30:32    Cancelled    Mobile App
138114  ORD-252033  2022-04-06   14:50:07    Completed  Social Media
138115  ORD-528577  2022-11-23   11:46:00    Completed    Mobile App

        customer_id     customer_name  customer_age  gender customer_segment  \
0       CUST-003102      Jasmine Ryan            55    Male         Consumer
1       CUST-003124       Scott Chase            26    Male          Premium
2       CUST-012496      Marc Wheeler            69  Female          Premium
3       CUST-023928    Jennifer Smith            65    Male         Consumer
4       CUST-012730      Jessica Wang            34  Female         Consumer
...             ...               ...           ...     ...              ...
138111  CUST-007151        Donna Ruiz            41  Female         Consumer
138112  CUST-006686    Jeremy Aguirre            40    Male          Premium
138113  CUST-017497  Timothy Williams            39  Female         Consumer
138114  CUST-005723    Charles Hanson            46  Female         Consumer
138115  CUST-006809       John Miller            28    Male         Consumer

        ... discount_amount tax_amount shipping_cost net_sales product_cost  \
0       ...          477.89      61.07         12.03    945.40       588.33
1       ...         1456.06     320.83          9.00   2018.41      2031.88
2       ...           97.30      29.79         13.05    468.35       257.73
3       ...           53.34      34.39         20.85    546.52       277.84
4       ...          133.63     421.35         23.03   2785.27      1231.88
...     ...             ...        ...           ...       ...          ...
138111  ...            8.84      14.28          6.15    224.42       101.77
138112  ...            0.00     147.30          9.18   2260.80      1246.73
138113  ...            0.00     372.37         26.94   2261.16       970.95
138114  ...          174.60     130.58         84.39   2080.38      1042.40
138115  ...          417.27     102.26          9.09   1572.22       884.46

         profit profit_margin_percentage customer_lifetime_value  \
0        345.04                    36.50                12459.68
1        -22.47                    -1.11                13032.48
2        197.57                    42.18                 6159.44
3        247.83                    45.35                 5638.30
4       1530.36                    54.94                13240.10
...         ...                      ...                     ...
138111   116.50                    51.91                18182.63
138112  1004.89                    44.45                10004.74
138113  1263.27                    55.87                16442.68
138114   953.59                    45.84                 8047.00
138115   678.67                    43.17                 4107.38

       is_repeat_customer customer_order_count
0                    True                   11
1                    True                   11
2                    True                    6
3                    True                    7
4                    True                    8
...                   ...                  ...
138111               True                   14
138112               True                   10
138113               True                   15
138114               True                    5
138115               True                    5

[138116 rows x 46 columns]>

In [8]:
print(df["customer_age"].mean())

45.86268064525471

In [9]:
print(df["customer_age"].median())

46.0

In [11]:
print(df["customer_age"].mode())

0    19
Name: customer_age, dtype: int64

In [12]:
print(df["customer_age"].var())

271.18434348997505

In [13]:
print(df["customer_age"].std())

16.467675716080123

In [14]:
print(df["customer_age"].min())

18

In [15]:
print(df["customer_age"].max())

74

In [16]:
print(df["customer_age"].count())

138116

In [17]:
print(df["tax_amount"].unique())

[ 61.07 320.83  29.79 ... 163.1  384.86 372.37]

In [18]:
print(df["tax_amount"].nunique())

43093

In [19]:
print(df["tax_amount"].value_counts())

tax_amount
15.56     23
11.06     22
6.04      22
22.07     21
40.86     21
          ..
569.46     1
319.30     1
163.10     1
384.86     1
372.37     1
Name: count, Length: 43093, dtype: int64

In [20]:
print(df.isnull())

        order_id  order_date  order_time  order_status  sales_channel  \
0          False       False       False         False          False
1          False       False       False         False          False
2          False       False       False         False          False
3          False       False       False         False          False
4          False       False       False         False          False
...          ...         ...         ...           ...            ...
138111     False       False       False         False          False
138112     False       False       False         False          False
138113     False       False       False         False          False
138114     False       False       False         False          False
138115     False       False       False         False          False

        customer_id  customer_name  customer_age  gender  customer_segment  \
0             False          False         False   False             False
1             False          False         False   False             False
2             False          False         False   False             False
3             False          False         False   False             False
4             False          False         False   False             False
...             ...            ...           ...     ...               ...
138111        False          False         False   False             False
138112        False          False         False   False             False
138113        False          False         False   False             False
138114        False          False         False   False             False
138115        False          False         False   False             False

        ...  discount_amount  tax_amount  shipping_cost  net_sales  \
0       ...            False       False          False      False
1       ...            False       False          False      False
2       ...            False       False          False      False
3       ...            False       False          False      False
4       ...            False       False          False      False
...     ...              ...         ...            ...        ...
138111  ...            False       False          False      False
138112  ...            False       False          False      False
138113  ...            False       False          False      False
138114  ...            False       False          False      False
138115  ...            False       False          False      False

        product_cost  profit  profit_margin_percentage  \
0              False   False                     False
1              False   False                     False
2              False   False                     False
3              False   False                     False
4              False   False                     False
...              ...     ...                       ...
138111         False   False                     False
138112         False   False                     False
138113         False   False                     False
138114         False   False                     False
138115         False   False                     False

        customer_lifetime_value  is_repeat_customer  customer_order_count
0                         False               False                 False
1                         False               False                 False
2                         False               False                 False
3                         False               False                 False
4                         False               False                 False
...                         ...                 ...                   ...
138111                    False               False                 False
138112                    False               False                 False
138113                    False               False                 False
138114                    False               False                 False
138115                    False               False                 False

[138116 rows x 46 columns]

In [21]:
print(df.isnull().sum())

order_id                         0
order_date                       0
order_time                       0
order_status                     0
sales_channel                    0
customer_id                      0
customer_name                    0
customer_age                     0
gender                           0
customer_segment                 0
customer_type                    0
customer_city                    0
customer_state                   0
customer_country                 0
region                           0
customer_postal_code             0
payment_method                   0
payment_status                   0
currency                         0
shipping_method                  0
warehouse                        0
delivery_days                24557
estimated_delivery_days      24557
delivery_status                  0
return_status               128654
return_reason               128654
customer_rating              24557
review_sentiment             24557
customer_review              24557
marketing_channel                0
campaign_name                83233
coupon_code                 110502
loyalty_points_earned            0
loyalty_points_redeemed          0
quantity                         0
gross_sales                      0
discount_amount                  0
tax_amount                       0
shipping_cost                    0
net_sales                        0
product_cost                     0
profit                           0
profit_margin_percentage         0
customer_lifetime_value          0
is_repeat_customer               0
customer_order_count             0
dtype: int64

In [22]:
print(df.isnull().mean()*100)

order_id                     0.000000
order_date                   0.000000
order_time                   0.000000
order_status                 0.000000
sales_channel                0.000000
customer_id                  0.000000
customer_name                0.000000
customer_age                 0.000000
gender                       0.000000
customer_segment             0.000000
customer_type                0.000000
customer_city                0.000000
customer_state               0.000000
customer_country             0.000000
region                       0.000000
customer_postal_code         0.000000
payment_method               0.000000
payment_status               0.000000
currency                     0.000000
shipping_method              0.000000
warehouse                    0.000000
delivery_days               17.779982
estimated_delivery_days     17.779982
delivery_status              0.000000
return_status               93.149237
return_reason               93.149237
customer_rating             17.779982
review_sentiment            17.779982
customer_review             17.779982
marketing_channel            0.000000
campaign_name               60.263112
coupon_code                 80.006661
loyalty_points_earned        0.000000
loyalty_points_redeemed      0.000000
quantity                     0.000000
gross_sales                  0.000000
discount_amount              0.000000
tax_amount                   0.000000
shipping_cost                0.000000
net_sales                    0.000000
product_cost                 0.000000
profit                       0.000000
profit_margin_percentage     0.000000
customer_lifetime_value      0.000000
is_repeat_customer           0.000000
customer_order_count         0.000000
dtype: float64

In [23]:
print(df.dropna())

Empty DataFrame
Columns: [order_id, order_date, order_time, order_status, sales_channel, customer_id, customer_name, customer_age, gender, customer_segment, customer_type, customer_city, customer_state, customer_country, region, customer_postal_code, payment_method, payment_status, currency, shipping_method, warehouse, delivery_days, estimated_delivery_days, delivery_status, return_status, return_reason, customer_rating, review_sentiment, customer_review, marketing_channel, campaign_name, coupon_code, loyalty_points_earned, loyalty_points_redeemed, quantity, gross_sales, discount_amount, tax_amount, shipping_cost, net_sales, product_cost, profit, profit_margin_percentage, customer_lifetime_value, is_repeat_customer, customer_order_count]
Index: []

[0 rows x 46 columns]

In [24]:
print(df.fillna(0))

          order_id  order_date order_time order_status sales_channel  \
0       ORD-301242  2023-11-06   16:37:47    Completed    Mobile App
1       ORD-773460  2025-12-24   01:22:36    Completed       Website
2       ORD-449374  2021-07-05   14:24:21    Completed    Mobile App
3       ORD-567636  2023-01-21   07:20:26    Completed  Social Media
4       ORD-820028  2022-05-13   09:46:21    Completed  Social Media
...            ...         ...        ...          ...           ...
138111  ORD-481534  2025-09-27   13:00:50    Completed    Mobile App
138112  ORD-487614  2023-07-22   09:13:25     Returned  Social Media
138113  ORD-248062  2025-09-08   18:30:32    Cancelled    Mobile App
138114  ORD-252033  2022-04-06   14:50:07    Completed  Social Media
138115  ORD-528577  2022-11-23   11:46:00    Completed    Mobile App

        customer_id     customer_name  customer_age  gender customer_segment  \
0       CUST-003102      Jasmine Ryan            55    Male         Consumer
1       CUST-003124       Scott Chase            26    Male          Premium
2       CUST-012496      Marc Wheeler            69  Female          Premium
3       CUST-023928    Jennifer Smith            65    Male         Consumer
4       CUST-012730      Jessica Wang            34  Female         Consumer
...             ...               ...           ...     ...              ...
138111  CUST-007151        Donna Ruiz            41  Female         Consumer
138112  CUST-006686    Jeremy Aguirre            40    Male          Premium
138113  CUST-017497  Timothy Williams            39  Female         Consumer
138114  CUST-005723    Charles Hanson            46  Female         Consumer
138115  CUST-006809       John Miller            28    Male         Consumer

        ... discount_amount tax_amount shipping_cost net_sales product_cost  \
0       ...          477.89      61.07         12.03    945.40       588.33
1       ...         1456.06     320.83          9.00   2018.41      2031.88
2       ...           97.30      29.79         13.05    468.35       257.73
3       ...           53.34      34.39         20.85    546.52       277.84
4       ...          133.63     421.35         23.03   2785.27      1231.88
...     ...             ...        ...           ...       ...          ...
138111  ...            8.84      14.28          6.15    224.42       101.77
138112  ...            0.00     147.30          9.18   2260.80      1246.73
138113  ...            0.00     372.37         26.94   2261.16       970.95
138114  ...          174.60     130.58         84.39   2080.38      1042.40
138115  ...          417.27     102.26          9.09   1572.22       884.46

         profit profit_margin_percentage customer_lifetime_value  \
0        345.04                    36.50                12459.68
1        -22.47                    -1.11                13032.48
2        197.57                    42.18                 6159.44
3        247.83                    45.35                 5638.30
4       1530.36                    54.94                13240.10
...         ...                      ...                     ...
138111   116.50                    51.91                18182.63
138112  1004.89                    44.45                10004.74
138113  1263.27                    55.87                16442.68
138114   953.59                    45.84                 8047.00
138115   678.67                    43.17                 4107.38

       is_repeat_customer customer_order_count
0                    True                   11
1                    True                   11
2                    True                    6
3                    True                    7
4                    True                    8
...                   ...                  ...
138111               True                   14
138112               True                   10
138113               True                   15
138114               True                    5
138115               True                    5

[138116 rows x 46 columns]

In [25]:
print(df.duplicated())

0         False
1         False
2         False
3         False
4         False
          ...
138111    False
138112    False
138113    False
138114    False
138115    False
Length: 138116, dtype: bool

In [27]:
print(df.duplicated().sum())

0

In [28]:
print(df.drop_duplicates())

          order_id  order_date order_time order_status sales_channel  \
0       ORD-301242  2023-11-06   16:37:47    Completed    Mobile App
1       ORD-773460  2025-12-24   01:22:36    Completed       Website
2       ORD-449374  2021-07-05   14:24:21    Completed    Mobile App
3       ORD-567636  2023-01-21   07:20:26    Completed  Social Media
4       ORD-820028  2022-05-13   09:46:21    Completed  Social Media
...            ...         ...        ...          ...           ...
138111  ORD-481534  2025-09-27   13:00:50    Completed    Mobile App
138112  ORD-487614  2023-07-22   09:13:25     Returned  Social Media
138113  ORD-248062  2025-09-08   18:30:32    Cancelled    Mobile App
138114  ORD-252033  2022-04-06   14:50:07    Completed  Social Media
138115  ORD-528577  2022-11-23   11:46:00    Completed    Mobile App

        customer_id     customer_name  customer_age  gender customer_segment  \
0       CUST-003102      Jasmine Ryan            55    Male         Consumer
1       CUST-003124       Scott Chase            26    Male          Premium
2       CUST-012496      Marc Wheeler            69  Female          Premium
3       CUST-023928    Jennifer Smith            65    Male         Consumer
4       CUST-012730      Jessica Wang            34  Female         Consumer
...             ...               ...           ...     ...              ...
138111  CUST-007151        Donna Ruiz            41  Female         Consumer
138112  CUST-006686    Jeremy Aguirre            40    Male          Premium
138113  CUST-017497  Timothy Williams            39  Female         Consumer
138114  CUST-005723    Charles Hanson            46  Female         Consumer
138115  CUST-006809       John Miller            28    Male         Consumer

        ... discount_amount tax_amount shipping_cost net_sales product_cost  \
0       ...          477.89      61.07         12.03    945.40       588.33
1       ...         1456.06     320.83          9.00   2018.41      2031.88
2       ...           97.30      29.79         13.05    468.35       257.73
3       ...           53.34      34.39         20.85    546.52       277.84
4       ...          133.63     421.35         23.03   2785.27      1231.88
...     ...             ...        ...           ...       ...          ...
138111  ...            8.84      14.28          6.15    224.42       101.77
138112  ...            0.00     147.30          9.18   2260.80      1246.73
138113  ...            0.00     372.37         26.94   2261.16       970.95
138114  ...          174.60     130.58         84.39   2080.38      1042.40
138115  ...          417.27     102.26          9.09   1572.22       884.46

         profit profit_margin_percentage customer_lifetime_value  \
0        345.04                    36.50                12459.68
1        -22.47                    -1.11                13032.48
2        197.57                    42.18                 6159.44
3        247.83                    45.35                 5638.30
4       1530.36                    54.94                13240.10
...         ...                      ...                     ...
138111   116.50                    51.91                18182.63
138112  1004.89                    44.45                10004.74
138113  1263.27                    55.87                16442.68
138114   953.59                    45.84                 8047.00
138115   678.67                    43.17                 4107.38

       is_repeat_customer customer_order_count
0                    True                   11
1                    True                   11
2                    True                    6
3                    True                    7
4                    True                    8
...                   ...                  ...
138111               True                   14
138112               True                   10
138113               True                   15
138114               True                    5
138115               True                    5

[138116 rows x 46 columns]

In [30]:
print(df[["customer_age","shipping_cost"]])

        customer_age  shipping_cost
0                 55          12.03
1                 26           9.00
2                 69          13.05
3                 65          20.85
4                 34          23.03
...              ...            ...
138111            41           6.15
138112            40           9.18
138113            39          26.94
138114            46          84.39
138115            28           9.09

[138116 rows x 2 columns]

In [32]:
print(df.iloc[0:5])

     order_id  order_date order_time order_status sales_channel  customer_id  \
0  ORD-301242  2023-11-06   16:37:47    Completed    Mobile App  CUST-003102
1  ORD-773460  2025-12-24   01:22:36    Completed       Website  CUST-003124
2  ORD-449374  2021-07-05   14:24:21    Completed    Mobile App  CUST-012496
3  ORD-567636  2023-01-21   07:20:26    Completed  Social Media  CUST-023928
4  ORD-820028  2022-05-13   09:46:21    Completed  Social Media  CUST-012730

    customer_name  customer_age  gender customer_segment  ... discount_amount  \
0    Jasmine Ryan            55    Male         Consumer  ...          477.89
1     Scott Chase            26    Male          Premium  ...         1456.06
2    Marc Wheeler            69  Female          Premium  ...           97.30
3  Jennifer Smith            65    Male         Consumer  ...           53.34
4    Jessica Wang            34  Female         Consumer  ...          133.63

  tax_amount shipping_cost net_sales product_cost   profit  \
0      61.07         12.03    945.40       588.33   345.04
1     320.83          9.00   2018.41      2031.88   -22.47
2      29.79         13.05    468.35       257.73   197.57
3      34.39         20.85    546.52       277.84   247.83
4     421.35         23.03   2785.27      1231.88  1530.36

  profit_margin_percentage customer_lifetime_value is_repeat_customer  \
0                    36.50                12459.68               True
1                    -1.11                13032.48               True
2                    42.18                 6159.44               True
3                    45.35                 5638.30               True
4                    54.94                13240.10               True

  customer_order_count
0                   11
1                   11
2                    6
3                    7
4                    8

[5 rows x 46 columns]

In [37]:
print(df[df["customer_age"]>30])

          order_id  order_date order_time order_status sales_channel  \
0       ORD-301242  2023-11-06   16:37:47    Completed    Mobile App
2       ORD-449374  2021-07-05   14:24:21    Completed    Mobile App
3       ORD-567636  2023-01-21   07:20:26    Completed  Social Media
4       ORD-820028  2022-05-13   09:46:21    Completed  Social Media
5       ORD-208728  2021-02-10   10:05:47      Pending       Website
...            ...         ...        ...          ...           ...
138110  ORD-874457  2022-11-16   09:38:04    Completed   Marketplace
138111  ORD-481534  2025-09-27   13:00:50    Completed    Mobile App
138112  ORD-487614  2023-07-22   09:13:25     Returned  Social Media
138113  ORD-248062  2025-09-08   18:30:32    Cancelled    Mobile App
138114  ORD-252033  2022-04-06   14:50:07    Completed  Social Media

        customer_id      customer_name  customer_age  gender customer_segment  \
0       CUST-003102       Jasmine Ryan            55    Male         Consumer
2       CUST-012496       Marc Wheeler            69  Female          Premium
3       CUST-023928     Jennifer Smith            65    Male         Consumer
4       CUST-012730       Jessica Wang            34  Female         Consumer
5       CUST-021468     Dominique Odom            41  Female         Consumer
...             ...                ...           ...     ...              ...
138110  CUST-004342  Kenneth Valentine            52  Female         Consumer
138111  CUST-007151         Donna Ruiz            41  Female         Consumer
138112  CUST-006686     Jeremy Aguirre            40    Male          Premium
138113  CUST-017497   Timothy Williams            39  Female         Consumer
138114  CUST-005723     Charles Hanson            46  Female         Consumer

        ... discount_amount tax_amount shipping_cost net_sales product_cost  \
0       ...          477.89      61.07         12.03    945.40       588.33
2       ...           97.30      29.79         13.05    468.35       257.73
3       ...           53.34      34.39         20.85    546.52       277.84
4       ...          133.63     421.35         23.03   2785.27      1231.88
5       ...          273.91     380.90         64.31   3375.24      1808.61
...     ...             ...        ...           ...       ...          ...
138110  ...          163.53      69.10          9.60   1065.82       704.12
138111  ...            8.84      14.28          6.15    224.42       101.77
138112  ...            0.00     147.30          9.18   2260.80      1246.73
138113  ...            0.00     372.37         26.94   2261.16       970.95
138114  ...          174.60     130.58         84.39   2080.38      1042.40

         profit profit_margin_percentage customer_lifetime_value  \
0        345.04                    36.50                12459.68
2        197.57                    42.18                 6159.44
3        247.83                    45.35                 5638.30
4       1530.36                    54.94                13240.10
5       1502.32                    44.51                 5615.09
...         ...                      ...                     ...
138110   352.10                    33.04                 5273.57
138111   116.50                    51.91                18182.63
138112  1004.89                    44.45                10004.74
138113  1263.27                    55.87                16442.68
138114   953.59                    45.84                 8047.00

       is_repeat_customer customer_order_count
0                    True                   11
2                    True                    6
3                    True                    7
4                    True                    8
5                    True                    3
...                   ...                  ...
138110               True                    6
138111               True                   14
138112               True                   10
138113               True                   15
138114               True                    5

[106263 rows x 46 columns]

In [38]:
df.sort_values("customer_age")

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
40557,ORD-444593,2022-04-25,20:29:33,Completed,Social Media,CUST-016655,Isabella Anderson,18,Female,Premium,...,198.62,120.35,15.15,1854.88,1143.11,696.62,37.56,13301.73,True,11
101086,ORD-770616,2024-10-21,07:46:31,Completed,Marketplace,CUST-003015,John Gomez,18,Female,Premium,...,9.57,25.01,15.51,397.87,180.43,201.93,50.75,2461.20,True,6
83581,ORD-416455,2023-05-04,00:18:15,Completed,Marketplace,CUST-011535,Lisa Rubio,18,Female,Business,...,140.88,48.91,11.25,758.91,414.11,333.55,43.95,1882.90,True,3
108843,ORD-264499,2025-03-07,03:43:29,Pending,Mobile App,CUST-005906,Christopher Nguyen,18,Female,Premium,...,87.04,87.29,2.79,1337.07,648.10,686.18,51.32,8629.94,True,10
135208,ORD-160998,2021-05-12,18:46:16,Completed,Website,CUST-002639,Taylor Phillips,18,Female,Consumer,...,35.85,42.10,32.20,284.82,103.66,148.96,52.30,1904.43,True,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46821,ORD-371204,2022-06-14,19:28:59,Completed,Marketplace,CUST-008312,William Wells,74,Male,VIP,...,123.73,44.62,9.35,691.45,402.39,279.71,40.45,6161.07,True,7
83279,ORD-193081,2022-11-06,06:30:06,Pending,Website,CUST-005658,Hannah Smith,74,Male,Consumer,...,703.18,115.89,12.79,1784.31,1490.94,280.58,15.72,10821.82,True,10
24364,ORD-649837,2022-12-18,03:40:28,Completed,Marketplace,CUST-022883,Lisa Sanders,74,Male,Premium,...,496.51,184.52,4.93,1608.84,924.93,678.98,42.20,9366.73,True,4
10463,ORD-742841,2023-11-06,12:07:34,Completed,Website,CUST-014245,Charles Hunter,74,Non-Binary,Consumer,...,841.45,86.36,74.88,1395.11,939.39,380.84,27.30,9410.50,True,7
125724,ORD-768332,2021-06-03,19:19:15,Pending,Mobile App,CUST-009963,Jessica Thomas,74,Female,Consumer,...,6.12,8.92,10.47,66.35,20.71,35.17,53.01,7619.79,True,9

In [39]:
df.rename(columns={"customer_age":"age"})

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138111,ORD-481534,2025-09-27,13:00:50,Completed,Mobile App,CUST-007151,Donna Ruiz,41,Female,Consumer,...,8.84,14.28,6.15,224.42,101.77,116.50,51.91,18182.63,True,14
138112,ORD-487614,2023-07-22,09:13:25,Returned,Social Media,CUST-006686,Jeremy Aguirre,40,Male,Premium,...,0.00,147.30,9.18,2260.80,1246.73,1004.89,44.45,10004.74,True,10
138113,ORD-248062,2025-09-08,18:30:32,Cancelled,Mobile App,CUST-017497,Timothy Williams,39,Female,Consumer,...,0.00,372.37,26.94,2261.16,970.95,1263.27,55.87,16442.68,True,15
138114,ORD-252033,2022-04-06,14:50:07,Completed,Social Media,CUST-005723,Charles Hanson,46,Female,Consumer,...,174.60,130.58,84.39,2080.38,1042.40,953.59,45.84,8047.00,True,5
138115,ORD-528577,2022-11-23,11:46:00,Completed,Mobile App,CUST-006809,John Miller,28,Male,Consumer,...,417.27,102.26,9.09,1572.22,884.46,678.67,43.17,4107.38,True,5

In [47]:
df.groupby("customer_id")

In [49]:
df.head()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count,Bonus
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,1.203,12.03,945.40,588.33,345.04,36.50,12459.68,True,11,1.203
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,0.900,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11,0.900
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,1.305,13.05,468.35,257.73,197.57,42.18,6159.44,True,6,1.305
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,2.085,20.85,546.52,277.84,247.83,45.35,5638.30,True,7,2.085
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,2.303,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8,2.303

In [50]:
df.tail()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count,Bonus
138111,ORD-481534,2025-09-27,13:00:50,Completed,Mobile App,CUST-007151,Donna Ruiz,41,Female,Consumer,...,0.615,6.15,224.42,101.77,116.50,51.91,18182.63,True,14,0.615
138112,ORD-487614,2023-07-22,09:13:25,Returned,Social Media,CUST-006686,Jeremy Aguirre,40,Male,Premium,...,0.918,9.18,2260.80,1246.73,1004.89,44.45,10004.74,True,10,0.918
138113,ORD-248062,2025-09-08,18:30:32,Cancelled,Mobile App,CUST-017497,Timothy Williams,39,Female,Consumer,...,2.694,26.94,2261.16,970.95,1263.27,55.87,16442.68,True,15,2.694
138114,ORD-252033,2022-04-06,14:50:07,Completed,Social Media,CUST-005723,Charles Hanson,46,Female,Consumer,...,8.439,84.39,2080.38,1042.40,953.59,45.84,8047.00,True,5,8.439
138115,ORD-528577,2022-11-23,11:46:00,Completed,Mobile App,CUST-006809,John Miller,28,Male,Consumer,...,0.909,9.09,1572.22,884.46,678.67,43.17,4107.38,True,5,0.909

In [51]:
df.shape

(138116, 47)